version: 0.2

env:
  git-credential-helper: yes
  shell: bash
  variables:
    DIRECTORY_TO_BUILD: "dir1"

phases:
  install:
    commands:
      - echo Fetching Git metadata...
      - ls -Al
      - CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - |
        IGNORE_LIST=($(cat build-ignore.txt))
        for file in $CHANGED_FILES
        do
          if [[ ${file} == ${DIRECTORY_TO_BUILD}/* && ! " ${IGNORE_LIST[@]} " =~ " ${file} " ]]; then
            echo "File ${file} is not in the ignore list and is in the ${DIRECTORY_TO_BUILD}. Proceeding with build..."
            break
          fi
        done
        if [[ -z ${PROCEED_BUILD} ]]; then
          echo "Only ignored files were modified or no changes in ${DIRECTORY_TO_BUILD}. Exiting build..."
          exit 0
        fi
      - apt-get update -y
  pre_build:
    commands:
      - echo Pre_build Phase
      - echo "$(hostname -i) local.test" >> /etc/hosts
      - cat /etc/hosts
  build:
    commands:
      - echo Build Phase
  post_build:
    commands:
      - echo Post Build Phase
